const fs = require('fs');
const path = require('path');
const file = path.join(process.env.USERPROFILE,'Desktop','portale-mazzini','src','App.jsx');
const lines = fs.readFileSync(file,'utf8').split('\n');
console.log('=== Riga 411 (nav) ===');
lines.slice(408,415).forEach((l,i)=>console.log((409+i)+': '+l));
console.log('\n=== Righe 420-430 (router) ===');
lines.slice(419,430).forEach((l,i)=>console.log((420+i)+': '+l));
console.log('\n=== Righe 451-465 (AdminCondominii) ===');
lines.slice(450,465).forEach((l,i)=>console.log((451+i)+': '+l));
console.log('\n=== Riga 825 (sendReminders) ===');
lines.slice(822,828).forEach((l,i)=>console.log((823+i)+': '+l));
